alias vi='/usr/bin/vim'
alias forge='source ~/forge/bin/activate'
alias mitx='source forge/bin/activate && cd ~/Dropbox/6.86x'
alias go='source forge/bin/activate && cd ~/scripts'
alias mvault2='sudo mount -t cifs -o credentials=/root/.jotunheim,uid=1000,gid=1000 //192.168.1.225/vault2 /mnt/vault2'
alias mdraupnir='sudo mount -t cifs -o credentials=/root/.myrkheim,uid=1000,gid=1000 //192.168.1.176/draupnir /mnt/draupnir'
alias mjshare='sudo mount -t cifs -o credentials=/root/.jotunheim,uid=1000,gid=1000 //192.168.1.225/shared /mnt/jotunheim'
alias mandvaranaut='sudo mount -t cifs -o credentials=/root/.myrkheim,uid=1000,gid=1000 //192.168.1.245/andvaranaut /mnt/andvaranaut'
alias gitssh='eval $(ssh-agent) && ssh-add ~/.ssh/git_personal_rsa'
alias gitencode='python ~/scripts/encode.py'
alias gitdecode='python ~/scripts/decode.py'
alias gitpush='~/scripts/gitpush.sh'

